export const SEED={
  projects:[
    {id:"p-vivo",name:"Rigô Controle — POC VIVO",area:"Patagon AI",status:"doing",description:"POC WhatsApp via Meta CTWA + Google Search para Telefônica/Vivo.",notes:"## Próximos passos\n- Assinar contrato (cláusula SLA pendente)\n- Implementar CAPI Meta\n- Go-live com canal WhatsApp\n\n## Contexto\nPrimeiro grande cliente enterprise da Patagon. Contrato em negociação com equipe jurídica.",goalId:"g1",createdAt:"2026-02-01T00:00:00Z"},
    {id:"p-imob",name:"Agente Imobiliário LATAM",area:"Patagon AI",status:"doing",description:"IA conversacional para corretoras. Benchmark 81K+ leads.",notes:"## Status\nBenchmark pronto. Pitch Golden Lake agendado.\n\n## Dados-chave\n- 81.247 leads analisados\n- Taxa qualificação: +340%\n- Custo por lead: -62%",goalId:"g4",createdAt:"2026-02-10T00:00:00Z"},
    {id:"p-agency",name:"Agency Channel Program",area:"Patagon AI",status:"todo",description:"Canal de parceiros agências. Estruturar comissões e onboarding.",notes:"",goalId:"g5",createdAt:"2026-03-01T00:00:00Z"},
    {id:"p-mazul",name:"Mazul — Lupeon + Lend.Tech",area:"Mazul Solutions",status:"doing",description:"Cadências LinkedIn, scripts Reels, relatórios semanais.",notes:"## Clientes ativos\n- **Lupeon**: Cadência 4.5 Tier 3. 12 leads/semana\n- **Lend.Tech**: B2B fintech. Foco em CFOs e controladoria\n\n## Deliverables pendentes\n- 36 scripts Reels (18 entregues)\n- Relatório semanal até sexta",goalId:"g2",createdAt:"2026-01-15T00:00:00Z"},
    {id:"p-lf",name:"LinkedFlow SaaS",area:"Mazul Solutions",status:"todo",description:"Plataforma SaaS automação LinkedIn outreach.",notes:"## Ideia\nTirar a expertise de outreach LinkedIn da Mazul e transformar em produto. MVP: dashboard de cadências + analytics.\n\nAguardando janela de execução (Q3 2026).",goalId:null,createdAt:"2026-02-20T00:00:00Z"},
    {id:"p-mh",name:"minhahistoria.app",area:"Indie",status:"doing",description:"Livros infantis personalizados. POD via Gelato/UICLAP.",notes:"## Status atual\n- Gelato integração: 60%\n- Landing /magica: wireframe pronto\n- Lei Rouanet: documentação em andamento\n- Copa 2026 pitch Cimed: deck em revisão",goalId:"g3",createdAt:"2025-11-01T00:00:00Z"},
    {id:"p-dg",name:"DocGen",area:"Indie",status:"todo",description:"SaaS geração de documentos com IA.",notes:"",goalId:null,createdAt:"2026-03-10T00:00:00Z"},
    {id:"p-yt",name:"YouTube — Fundadores BR de IA",area:"Marca Pessoal",status:"doing",description:"Entrevistas com fundadores brasileiros de IA/SaaS.",notes:"## Entrevistas agendadas\n- Sabrina (Plink) — gravar até 20/03\n- Matheus Weigand (Getdemo) — confirmar data\n\n## Formato\nZoom 30min + edição CapCut + thumbnail Canva",goalId:"g6",createdAt:"2026-02-15T00:00:00Z"},
  ],
  tasks:[
    {id:"t1",title:"Finalizar contrato VIVO",projectId:"p-vivo",priority:"alta",done:false,dueDate:"2026-03-22",notes:"Revisar cláusula SLA e exclusividade de canal",goalId:"g1",createdAt:"2026-03-15T10:00:00Z"},
    {id:"t2",title:"Implementar CAPI no POC (Meta)",projectId:"p-vivo",priority:"alta",done:false,dueDate:"2026-03-25",notes:"Depende da aprovação do contrato",goalId:"g1",createdAt:"2026-03-15T10:00:00Z"},
    {id:"t3",title:"Follow-up Capim — migração Darwin→Patagon",projectId:"p-vivo",priority:"media",done:false,dueDate:"2026-03-22",notes:"",goalId:null,createdAt:"2026-03-16T10:00:00Z"},
    {id:"t4",title:"Pitch deck Golden Lake — Imob",projectId:"p-imob",priority:"media",done:false,dueDate:"2026-03-30",notes:"Usar benchmark 81K leads como âncora",goalId:"g4",createdAt:"2026-03-12T10:00:00Z"},
    {id:"t5",title:"Landing page Patagon Imobiliário",projectId:"p-imob",priority:"media",done:false,dueDate:"2026-04-05",notes:"",goalId:"g4",createdAt:"2026-03-10T10:00:00Z"},
    {id:"t6",title:"Entregar 36 scripts Reels — Mazul",projectId:"p-mazul",priority:"media",done:false,dueDate:"2026-03-28",notes:"18 aprovados, falta segunda metade",goalId:"g2",createdAt:"2026-03-13T10:00:00Z"},
    {id:"t7",title:"Relatório semanal Lupeon (LinkedIn)",projectId:"p-mazul",priority:"media",done:false,dueDate:"2026-03-21",notes:"",goalId:null,createdAt:"2026-03-17T10:00:00Z"},
    {id:"t8",title:"Relatório semanal Lend.Tech",projectId:"p-mazul",priority:"media",done:true,dueDate:"2026-03-21",notes:"",goalId:null,createdAt:"2026-03-17T10:00:00Z"},
    {id:"t9",title:"Entrevista YT — Sabrina (Plink)",projectId:"p-yt",priority:"alta",done:false,dueDate:"2026-03-20",notes:"Gravar Zoom, editar CapCut",goalId:"g6",createdAt:"2026-03-14T10:00:00Z"},
    {id:"t10",title:"Entrevista YT — Matheus Weigand",projectId:"p-yt",priority:"media",done:false,dueDate:"2026-04-02",notes:"",goalId:"g6",createdAt:"2026-03-14T10:00:00Z"},
    {id:"t11",title:"Integração POD Gelato",projectId:"p-mh",priority:"baixa",done:false,dueDate:"2026-04-10",notes:"",goalId:"g3",createdAt:"2026-03-08T10:00:00Z"},
    {id:"t12",title:"Landing /magica — minhahistoria",projectId:"p-mh",priority:"baixa",done:false,dueDate:"2026-04-15",notes:"Conversão orgânica imersiva",goalId:"g3",createdAt:"2026-03-05T10:00:00Z"},
  ],
  goals:[
    {id:"g1",title:"Fechar contrato Patagon × VIVO",category:"Produto",status:"ativo",progress:0,deadline:"2026-04-01",description:"POC aprovado → contrato assinado → go live com CAPI",progressMode:"tasks",keyResults:[],createdAt:"2026-02-01T00:00:00Z"},
    {id:"g2",title:"R$30k MRR — Mazul",category:"Financeiro",status:"ativo",progress:48,deadline:"2026-06-30",description:"Escalar base de clientes de outreach LinkedIn",progressMode:"keyResults",keyResults:[{id:"k2a",title:"Clientes ativos",current:2,target:6,unit:"clientes"},{id:"k2b",title:"MRR",current:14000,target:30000,unit:"R$"}],createdAt:"2026-01-01T00:00:00Z"},
    {id:"g3",title:"Lançar minhahistoria v2 com POD",category:"Produto",status:"ativo",progress:0,deadline:"2026-05-15",description:"POD ativo, /magica live, parceria Copa 2026",progressMode:"tasks",keyResults:[],createdAt:"2026-01-15T00:00:00Z"},
    {id:"g4",title:"3 clientes enterprise — Patagon Imob",category:"Produto",status:"ativo",progress:0,deadline:"2026-07-01",description:"Golden Lake + 2 corretoras LATAM",progressMode:"tasks",keyResults:[],createdAt:"2026-02-10T00:00:00Z"},
    {id:"g5",title:"3 agências no Agency Channel",category:"Produto",status:"ativo",progress:10,deadline:"2026-08-01",description:"Canal de parceiros Patagon AI",progressMode:"manual",keyResults:[],createdAt:"2026-03-01T00:00:00Z"},
    {id:"g6",title:"1.000 subs YouTube até junho",category:"Marca Pessoal",status:"ativo",progress:0,deadline:"2026-06-30",description:"Canal de entrevistas fundadores BR de IA",progressMode:"keyResults",keyResults:[{id:"k6a",title:"Inscritos",current:120,target:1000,unit:"subs"},{id:"k6b",title:"Vídeos publicados",current:2,target:12,unit:"vídeos"}],createdAt:"2026-02-15T00:00:00Z"},
    {id:"g7",title:"Lançar LinkedFlow MVP",category:"Produto",status:"pausado",progress:15,deadline:"2026-09-01",description:"SaaS automação LinkedIn. Aguardando janela.",progressMode:"manual",keyResults:[],createdAt:"2026-01-01T00:00:00Z"},
  ],
  content:[
    {id:"c1",title:"Sabrina (Plink): distribuindo IA para 50k usuários",channel:"youtube",type:"Vídeo",status:"review",scheduledDate:"2026-03-28",description:"Entrevista gravada. Edição em andamento.",createdAt:"2026-03-08T00:00:00Z"},
    {id:"c2",title:"Fundadores BR de IA: Matheus Weigand (Getdemo)",channel:"youtube",type:"Vídeo",status:"idea",scheduledDate:"2026-04-10",description:"",createdAt:"2026-03-10T00:00:00Z"},
    {id:"c3",title:"Vibe coding: armadilhas que ninguém te conta",channel:"linkedin",type:"Post",status:"draft",scheduledDate:"2026-03-22",description:"Thread sobre vibe coding sem contexto técnico",createdAt:"2026-03-15T00:00:00Z"},
    {id:"c4",title:"IA, Cultura e o Novo Modelo de Agência",channel:"linkedin",type:"Carrossel",status:"ready",scheduledDate:"2026-03-20",description:"Resumo webinar Vinicius Ribeiro. 10 slides.",createdAt:"2026-03-12T00:00:00Z"},
    {id:"c5",title:"36 ideias de Reels usando IA",channel:"instagram",type:"Reel",status:"published",scheduledDate:"2026-03-15",description:"2.3k views.",createdAt:"2026-03-01T00:00:00Z"},
    {id:"c6",title:"Como automatizei meu LinkedIn e gerei 40+ leads",channel:"linkedin",type:"Post",status:"published",scheduledDate:"2026-02-20",description:"",createdAt:"2026-02-20T00:00:00Z"},
    {id:"c7",title:"Meu stack de ferramentas de IA para 2026",channel:"youtube",type:"Short",status:"idea",scheduledDate:"2026-04-05",description:"15 ferramentas. Formato talking head.",createdAt:"2026-03-17T00:00:00Z"},
    {id:"c8",title:"Case Patagon: IA aumentou 3x qualificação de leads",channel:"linkedin",type:"Carrossel",status:"draft",scheduledDate:"2026-04-01",description:"Dados benchmark 200K+ conversas automotive",createdAt:"2026-03-16T00:00:00Z"},
  ],
  tools:[
    {id:"tl1",name:"Claude",category:"IA",status:"on",url:"https://claude.ai",desc:"Principal LLM. Core de todos os projetos."},
    {id:"tl2",name:"ChatGPT",category:"IA",status:"on",url:"https://chat.openai.com",desc:"Backup e casos específicos."},
    {id:"tl3",name:"n8n",category:"Automação",status:"on",url:"https://n8n.io",desc:"Automações self-hosted. Core infra Patagon."},
    {id:"tl4",name:"Make",category:"Automação",status:"warn",url:"https://make.com",desc:"Automações legadas. Migrando para n8n."},
    {id:"tl5",name:"Vercel",category:"Deploy",status:"on",url:"https://vercel.com",desc:"Deploy Next.js."},
    {id:"tl6",name:"Supabase",category:"Database",status:"on",url:"https://supabase.com",desc:"DB principal. minhahistoria + DocGen."},
    {id:"tl7",name:"Cal.com",category:"Agenda",status:"on",url:"https://cal.com",desc:"Agendamento de calls e entrevistas."},
    {id:"tl8",name:"Resend",category:"Email",status:"on",url:"https://resend.com",desc:"Email transacional."},
    {id:"tl9",name:"CapCut",category:"Vídeo",status:"on",url:"https://capcut.com",desc:"Edição Reels e Shorts."},
    {id:"tl10",name:"Notion",category:"Docs",status:"on",url:"https://notion.so",desc:"Wikis e documentação."},
    {id:"tl11",name:"Canva",category:"Design",status:"on",url:"https://canva.com",desc:"Materiais visuais."},
    {id:"tl12",name:"Luma",category:"Eventos",status:"on",url:"https://lu.ma",desc:"Webinars e eventos ao vivo."},
  ],
};
